# Generated by Django 5.1.6 on 2025-02-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.TextField(),
        ),
    ]
